{% set name = "rlic" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rlic-{{ version }}.tar.gz
  sha256: d28b1efe64fbc3e28934457d8eb3f0fdb5431ac4dc33fc129a8a6642958cc406

build:
  number: 0

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - maturin
  host:
    - python
    - maturin >=1.0,<2,!=1.9.1
    - pip
  run:
    - python
    - numpy >=1.21.0
    - exceptiongroup >=1.0.0  # [py<311]

test:
  source_files:
    - tests
  imports:
    - rlic
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - pip
    - pytest

about:
  summary: A minimal Line Integral Convolution extension for NumPy, written in Rust
  home: https://github.com/neutrinoceros/rlic
  license: MIT
  license_file:
    - LICENSE/LICENSE_rlic
    - LICENSE/LICENSE_vectorplot
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - neutrinoceros
