{% set name = "rlic" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rlic-{{ version }}.tar.gz
  sha256: cfca1ed344f6fc664576cb7f5a18dc4586bd41e2ab7ddf8b439617eeef9b9cb3

build:
  number: 0
  python_version_independent: true  # [is_abi3]
  skip: true  # [is_abi3 and not is_python_min]
    
requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
    - cmake
    - make
    - maturin
  host:
    - python-abi3  # [is_abi3]
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - numpy >=1.22.0
    - exceptiongroup >=1.0.0  # [py<311]

test:
  requires:
    - pip
    - pytest
    - abi3audit  # [is_abi3]
  source_files:
    - tests
  imports:
    - rlic
  commands:
    - pip check
    - pytest -ra tests
    - abi3audit $SP_DIR/rlic/_core.abi3.so -s -v --assume-minimum-abi3 {{ python_min }}  # [unix and is_abi3]
    - abi3audit %SP_DIR%/rlic/_core.pyd -s -v --assume-minimum-abi3 {{ python_min }}  # [win and is_abi3]

about:
  summary: A minimal Line Integral Convolution extension for NumPy, written in Rust
  home: https://github.com/neutrinoceros/rlic
  license: MIT
  license_file:
    - LICENSE_rlic
    - LICENSE_vectorplot
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - neutrinoceros
